komga:
  baseUri: ${env:KOMF_KOMGA_BASE_URI:-"http://localhost:8080"}
  komgaUser: ${env:KOMF_KOMGA_USER:-"admin@example.org"}
  komgaPassword: ${env:KOMF_KOMGA_PASSWORD:-"admin"}
  eventListener:
    enabled: ${env:KOMF_KOMGA_EVENT_LISTENER_ENABLED:-true}
    libraries: []
metadataProviders:
  mal:
    clientId: ${env:KOMF_MAL_CLIENT_ID:-""}
    priority: ${env:KOMF_MAL_PRIORITY:-20}
    enabled: ${env:KOMF_MAL_ENABLED:-false}
  mangaUpdates:
    priority: ${env:KOMF_MANGAUPDATES_PRIORITY:-10}
    enabled: ${env:KOMF_MANGAUPDATES_ENABLED:-true}
server:
  port: ${env:KOMF_SERVER_PORT:-8085}
logLevel: ${env:KOMF_LOG_LEVEL:-INFO}
