komga:
  baseUri: "http://localhost:8080"
  komgaUser: "admin@example.org"
  komgaPassword: "admin"
  eventListener:
    enabled: true
    libraries: [ ]
  metadataUpdate:
    bookThumbnails: false
    seriesThumbnails: true
database:
  file: ./database.sqlite
metadataProviders:
  mangaUpdates:
    priority: 10
    enabled: true
  mal:
    clientId: ""
    priority: 20
    enabled: false
  nautiljon:
    priority: 30
    enabled: false
    fetchBookMetadata: false
server:
  port: 8085
logLevel: INFO
