komga:
  baseUri: "http://localhost:8080"
  komgaUser: "admin@example.org"
  komgaPassword: "admin"
  eventListener:
    enabled: true
    libraries: []
database:
  file: ${env:KOMF_CONFIG_DIR:-.}/database.sqlite
metadataProviders:
  mal:
    clientId: ""
    priority: 20
    enabled: false
  mangaUpdates:
    priority: 10
    enabled: true
server:
  port: 8085
logLevel: INFO
